- name: Terminate every running instance in a region. Use with EXTREME caution.
  hosts: local
  become: yes
  vars:
    instances:
    - mysql
    - backend
    - frontend

  tasks:
    - name: Delete ec2 insatnces
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        region: us-east-1
        state: absent
        filters:
          instance-state-name: running
        loop: "{{ instances }}"