- name: Terminate EC2 running instances by name
  hosts: local
  become: yes
  vars:
    instances:
    - mysql
    - backend
    - frontend
  tasks:
    - name: Find ec2 insatnces by name tag
      amazon.aws.ec2_instance_info:
        filter:
          tag:Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_info
    - name: print ec2_info
      ansible.builtin.debug:
        msg: "{{ ec2_info }}"
    - name: Terminate EC2 instances
      amazon.aws.ec2_instance:
        instance_ids: "{{ item.instances[0].instance_id }}"
        state: absent
      when: item.instances | length > 0
      loop: "{{ ec2_info.results }}"
