- name: create EC2 and R53 for Expense applicatoin
  hosts: local
  #become: yes
  connection: local
  vars:
    instances:
    - mysql
    - backend
    - frontend
    ansible_python_interpreter: /usr/bin/python3.9
  tasks:
    - name: import the required Python library (botocore and boto3)
      ansible.builtin.pip:
        name:
          - botocore
          - boto3
        executable: pip3.9
    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: t3.micro
        image_id: ami-09c813fb71547fc4f
        #count: 3
        region: us-east-1
        vpc_subnet_id: subnet-07bfec4c75466fbda
      loop: "{{ instances }}"
      register: ec2_instances

    - name: Print the ec2 instances
      ansible.builtin.debug:
        msg: "{{ ec2_instances }}"
    